ministryofjustice/hmpps-book-a-video-link-api

build.gradle.kts, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, src/main/resources/application-local.yml, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/JwtAuthHelper.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/NotFoundTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/wiremock/HmppsAuthMockServer.kt
This change includes the basics for getting integration with HMPPS auth using a common shared HMPPS Kotlin library.  
This takes away a lot of the boiler plate code we would otherwise have to include.  It also allows for consistency moving forwards should things change i.e. the share component can pick up this responsibility.
If push comes to shove we can use our own instead but it shouldn't come to that if we use the common one.
=> BAVL-67 adding config for HMPPS auth integration.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/WebClientConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/health/HmppsAuthHealthPingCheck.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/health/HealthCheckTest.kt, src/test/resources/application-test.yml
Adds health check for recently added HMPPS auth integration.
Any services we rely on should be added as health checks going forwards.
=> BAVL-67 adding health check for HMPPS auth.

build.gradle.kts, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/prisonersearch/PrisonerSearchClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/WebClientConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/health/HealthPingCheck.kt, src/main/resources/application-local.yml, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/prisonersearch/PrisonerSearchClientTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/health/HealthCheckTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/wiremock/HmppsAuthMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/wiremock/LocationsInsidePrisonApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/wiremock/MockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/wiremock/PrisonerSearchApiMockServer.kt, src/test/resources/application-test.yml
This change will allow our service to make calls to the external prisoner search API for checking the details of a prisoner related to video link bookings.
Note the original intention of this change was to generate the types for the prisoner search API.  However open API seemed to have an issue (bug) with generating it and I don't want to spend too long trying to see if there is a solution at this point in time.
=> BAVL-71 adding the necessary client for making calls to the prisoner search API.

README.md, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/EmailConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/GovNotifyEmailService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/GovNotifyEmailServiceTest.kt
This change provides a simple implementation for sending emails via Gov Notify.
The service will likely need further changes but hopefully this gives us a good initial footing.
=> BAVL-14 this change adds a simple implementation for the Gov Notify email service.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/EmailConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/GovNotifyEmailService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/health/Assertions.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/GovNotifyEmailServiceTest.kt
Handle email failures gracefully so the caller can decide on course of action if/when it happens.
The change also now returns the unique reference associated with an email send from gov notify so we can record it against the email notification in the notifications table.
=> BAVL-14 handle the sending of email errors gracefully, do not just throw error if send fails, let the caller decided on course of action.

helm_deploy/values-dev.yaml, src/main/resources/application-dev.yml, src/main/resources/application-local.yml, src/main/resources/application.yml, src/main/resources/migrations/common/V2024.04.22__baseline_tables.sql
The changes adds the notification id returned by gov notify to our own notifications table.
This will be useful down the line if we need to investigate any potential issues with notifications.  It also gives us the option to consider implementing a callback endpoint which gov notify can call to say whether some has actually been delivered or not.
=> BAVL-14 updates the notification table to include a reference to the associated gov notify notifications.

helm_deploy/hmpps-book-a-video-link-api/values.yaml
This secret for the API key has been added to the dev k8s namespace.  I would suggest verifying this prior to approving the PR.
=> BAVL-14 add gov notify api key environment var. Still need template IDs adding when we know them.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/CreateVideoBookingRequest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/CreateVideoBookingRequestTest.kt
The change adds the necessary attributes to the create journey request to identify court and probation bookings.
=> BAVL-97 adds the columns/identifiers needed for courts and probation to the creation request.

src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/Assertions.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/VideoLinkBookingIntegrationTest.kt
The is the first end to end integration test which exercises the persistence of a court and probation booking to the database.
It does not create any appointments, this is next on the agenda.
I was thinking of not bothering with Controller dedicated tests as we really end up writing almost the same as an integration test anyway.
=> BAVL-98 first simple integration test for the creation journey.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/common/LocalTimeExt.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/PrisonAppointment.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/VideoBooking.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/CreateVideoBookingRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/repository/PrisonAppointmentRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateVideoBookingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/ModelFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/VideoLinkBookingIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateVideoBookingServiceTest.kt
This change introduces the PrisonAppointment entity and also creates one as part of the probation booking/appointment creation journey.  There are still validation needs in this area, e.g. checking of location keys.
Court appointments are not created in these changes.
=> BAVL-98 changes introduces and persists the appointment for a probation team appointment. Still requires further validation checks.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/CreateVideoBookingRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateVideoBookingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/ModelFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/VideoLinkBookingIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateVideoBookingServiceTest.kt
This change now adds the creation of appointments for a court bookings.
There are further validation steps required but this gets the end to end flow in place.
=> BAVL-98 changes to persist the appointments for a court hearing booking. Still requires further validation checks.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/VideoBooking.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateVideoBookingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/EntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/ModelFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/VideoLinkBookingIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateVideoBookingServiceTest.kt
This change adds the missing comments field for the VideoBooking entity and also now checks the selected court or probation team are enabled prior to creating a booking.
=> BAVL-98 these changes fix the missing comments field and checks courts and probation teams are enabled.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/Prison.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/Prison.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/repository/PrisonRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/resource/PrisonsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/PrisonsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/mapping/PrisonMappers.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/EntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/PrisonsResourceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/PrisonsServiceTest.kt
Supply request parameter `enabledOnly=true` to limit just to those enabled for self-service video bookings.
The default is to return all prisons.
=> BAVL-133: Controller, service and repository methods to return a list of prisons

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/locationsinsideprison/LocationsInsidePrisonClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacade.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/VideoLinkBookingIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/wiremock/LocationsInsidePrisonApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacadeTest.kt
This changes a call to the locations api to use a new post endpoint for locations so we can make one call instead of many calls for locations.
It also corrects the (initial) email contact type.  There are still more emails to be sent on creation of a booking.
=> BAVL-128 correct email contact to owner for new court email and update locations api to use new endpoint.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/manageusers/ManageUsersClient.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/manageusers/ManageUsersClientTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/ModelFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/wiremock/ManageUsersApiMockServer.kt
Strictly speaking we should not need this (default call to users API should only return verified) but I have added as a precautionary measure given the change/impact is very small.
=> BAVL-134 added checks to ensure we only send owner emails to verified email addresses only.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/HmppsBookAVideoLinkApiExceptionHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/CreateVideoBookingRequest.kt, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/resource/VideoLinkBookingControllerTest.kt
So I struggled to get a unit or integration test to confirm these changes work, I have tested this manually.
Perhaps have a quick read [here](https://makemeengr.com/uuuu-versus-yyyy-in-datetimeformatter-formatting-pattern-codes-in-java/) and [here](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html).
=> BAVL-142 changes to prevent sumbission of invalid dates which would be otherwise be rounded as a result of default lenient dates.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/EmailConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/BookingContact.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/BookingContact.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingContactsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacade.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/GovNotifyEmailService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/mapping/BookingContactMappers.kt, src/main/resources/application.yml, src/main/resources/migrations/common/R__v_booking_contacts.sql, src/main/resources/migrations/common/V2024.04.22__baseline_tables.sql, src/main/resources/migrations/common/V2024.04.23__baseline_data.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/Courts.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/ModelFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/ProbationTeams.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/BookingContactsResourceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/VideoLinkBookingIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacadeTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/GovNotifyEmailServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/NewCourtBookingEmailTest.kt, src/test/resources/application-test.yml
These changes add in additional emails on the creation journey for prisons.
Two new prison emails have been added, one where we have a contact for a court and one where we don't have a court contact.
=> BAVL-128 updates to support sending emails to prisons on creation of booking.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/VideoAppointment.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/AvailabilityRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/response/AvailabilityResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/repository/VideoAppointmentRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/resource/AvailabilityController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AvailabilityFinderService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AvailabilityOptionsGenerator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AvailabilityService.kt, src/main/resources/application.yml, src/main/resources/migrations/common/R__v_video_appointments.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/AvailabilityResourceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AvailabilityServiceTest.kt
The availability check is called by the UI prior to creating bookings.
It checks that the prison rooms are free at the requested times, and if not will offer up to 3 alternatives (configurable).
It uses a new view of video appointments in the DB for a date and prison.
More tests for the OptionsFinderService are on their way in the next PR.
=> BAV-170 availability check and suggestions for free rooms at the prison

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/activitiesappointments/ActivitiesAppointmentsClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/prisonapi/PrisonApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/prisonersearch/PrisonerSearchClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/common/LocalDateTimeExt.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/AvailabilityRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacade.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/ManageExternalAppointmentsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/prisonapi/PrisonApiClientTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/ModelFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/wiremock/PrisonApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacadeTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/ManageExternalAppointmentsServiceTest.kt
These changes now mean we can establish the locations IDs from our location keys for creation of appointments in the activities and appointments api and prison api.
Note: we are still not actually raising events yet.  I have not wired in the calls to SQS and the cloud platform work is still missing.
=> BAVL-25 adding in the necessary calls to activities api and prison api for creation of appoinments.

helm_deploy/values-dev.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/DomainEvents.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/InboundEventsListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/ManageExternalAppointmentsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/OutboundEventsPublisher.kt
Flicks the switch to **ON** for creating bookings (appointments) in external services.
Gone a bit heavier on the logging just so we can see it though better in early stages.
=> BAVL-25 switching send/receive events on in dev.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/prisonapi/PrisonApiClient.kt
This is mirroring the behavior in whereabouts-api.  We already do this for appointment creation in prison-api.
=> BAVL-213 when cancelling (deleting) appointments in prison API we do not want the event in prison-api to be propagated.  This is the end of the road.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/ServiceName.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/repository/PrisonAppointmentRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/DomainEvents.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/InboundEventsListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/InboundEventsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/OutboundEventsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/PrisonerReleasedEventHandler.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/DomainEventTypeTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/InboundEventsServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/OutboundEventsServiceImplTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/PrisonerReleasedEventHandlerTest.kt
The intention is to add localstack integration test coverage in a separate PR.
We also need a cloud platform change to take place to listen for the release event. Until that happens the code for release events will not fire.
=> BAVL-235 adding support for processing of prisoner released events to handle potential cancellation of future bookings.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/common/LocalDateExt.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/common/StringExt.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/DomainEvents.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/OutboundEventsServiceImplTest.kt
The occurredAt is a an offset date time which we were not catering for.  This showed up a deserialisation issue when testing the release of a prisoner in dev with some video bookings.
=> BAVL-235 fixing offset datetime issue spotted during testing with real release event in dev.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/repository/PrisonAppointmentRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/PrisonerReleasedEventHandler.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/SqsIntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/InboundEventsIntegrationTest.kt
Missing brackets of JPQL query when looking for active bookings that could be cancelled.  Backed up with a test this time.
=> BAVL-235 missing brackets off query when looking for bookings that can be cancelled.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/prisonersearch/PrisonerSearchClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacade.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/ModelFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/InboundEventsIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/wiremock/PrisonerSearchApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacadeTest.kt
This change fixes an issue when a prisoner is release or transferred.
When looking up the prisoner from prisoner search we should be using the prisoners last prison id/code when looking up the prison details in our service otherwise they will not match.
=> BAVL-235 should be using the last known prison on release/transfer of prisoners when sending emails.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/repository/PrisonAppointmentRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AppointmentsService.kt, src/main/resources/migrations/common/V2024.04.22__baseline_tables.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/VideoLinkBookingIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AmendVideoBookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateVideoBookingServiceTest.kt
So this changes fixes the initial problem.  However we would potentially need different behavior if it were created by a prison user, as in we don't care about clashes at all when done by a prison user.
=> BAVL-246 changes to allow new bookings to be at the same date and time and location as cancelled ones, this is allowed.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/repository/BookingHistoryAppointmentRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/repository/PrisonAppointmentRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacade.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateVideoBookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/UserService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/DomainEvents.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/InboundEventsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/PrisonerMergedEventHandler.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/InboundEventsIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/UserServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/InboundEventsServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/PrisonerMergedEventHandlerTest.kt, src/test/resources/integration-test-data/seed-prisoner-merge.sql
This needs to be merged before the (yet to do) cloud platform change to listen for the actual event, otherwise messages can build up on the queue.
=> BAVL-250 changes to support the processing of prisoner merge events.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/locationsinsideprison/LocationsInsidePrisonClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/CacheConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CsvDataExtractionService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/PrisonsResourceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CsvDataExtractionServiceTest.kt
Changes to cache locations primarily for CSV extracts.
Also adding cap to prevent requesting more that 1 years worth of data.
=> BAVL-266 adding location caching and capping the max number of days of data to 1 year.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/repository/PrisonAppointmentRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AmendVideoBookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AppointmentsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateVideoBookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/RequestBookingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/Users.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/VideoLinkBookingIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AmendVideoBookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingHistoryServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateVideoBookingServiceTest.kt
These changes relax the rules regarding booking prison appointment creation/amending by prison users to align with Activities and Appointments which allows overlapping appointments.
Note external users cannot do this so any attempt to create overlapping will still be rejected.
=> BAVL-278 allow overlapping existing prison appointment creation/amending for prison users.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/common/PrecondionChecks.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/Court.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/AmendVideoBookingRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/resource/VideoLinkBookingController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AmendVideoBookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateVideoBookingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/EntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/VideoLinkBookingIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AmendVideoBookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateVideoBookingServiceTest.kt
Changes to prevent prison users from creating probation meetings and changing the court on an existing booking.
=> BAVL-283 prison users cannot create probation meetings and cannot change the court on an existing booking.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/locationsinsideprison/LocationsInsidePrisonClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/EmailConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacade.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/GovNotifyEmailService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/CourtEmailFactory.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/ProbationEmailFactory.kt, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/locationsinsideprison/LocationValidatorTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/EmailTemplatesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/ModelFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/AvailabilityResourceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/BookingContactsResourceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/ScheduleResourceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/VideoLinkBookingIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/wiremock/LocationsInsidePrisonApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacadeTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/GovNotifyEmailServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/CourtEmailFactoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/ProbationEmailFactoryTest.kt
This is the first PR for getting the probation email train going.  It will send a user and probation contact email on creation.
Need to add email support for prison contacts.
I will be adding the missing emails in separate PR's.
=> BAVL-284 send probation creation email to user when probation booking is made

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/EmailConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacade.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/GovNotifyEmailService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/ProbationEmailFactory.kt, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/EmailTemplatesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/VideoLinkBookingIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacadeTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/GovNotifyEmailServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/ProbationEmailFactoryTest.kt
Taken out probation email for probation contact, done in error.  Added two prison emails set on creation of a booking by an probation user.
=> BAVL-284 send prison emails on probation booking.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CsvDataExtractionService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/CsvDataExtractionIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CsvDataExtractionServiceTest.kt
Corrects probation column heading and changes mapping of `amend` events to `update` in the generated csv files.
=> BAVL-294 column heading change and mapping of AMEND to UPDATE to match old BVLS.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/resource/CourtsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/resource/ProbationTeamsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CourtsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateVideoBookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/ProbationTeamsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/CourtsResourceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/ProbationTeamsResourceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CourtsServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateVideoBookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/ProbationTeamsServiceTest.kt
Two new endpoints for all or enabled only courts and probation teams.
The existing enabled only endpoints for courts and probation are deprecated and will removed when UI's referencing them are changed to use the new endpoints.
=> BAVL-297 new endpoints to return enabled only or all courts and probations teams.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/HmppsBookAVideoLinkApiExceptionHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/VideoBooking.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/repository/ReferenceCodeRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/security/CaseloadAccess.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/UserService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/VideoLinkBookingsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/EntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/ModelFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/resource/VideoLinkBookingControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/security/CaseloadAccessKtTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/security/MockUserAndCaseload.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/UserServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/VideoLinkBookingsServiceTest.kt
Changes to limit access when getting bookings for prison users.
Access is forbidden if the prison users active caseload does not match the prison code for the booking.  Will return a 404 not a 403.
=> BAVL-280 restrict access to get bookings for prison users enforced by their active caseload.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateVideoBookingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/ModelFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/Users.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/BookingContactsResourceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/CourtsResourceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/ProbationTeamsResourceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/VideoLinkBookingIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/wiremock/HmppsAuthMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/wiremock/ManageUsersApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/resource/VideoLinkBookingControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/security/CaseloadAccessKtTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacadeTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateVideoBookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/VideoLinkBookingsServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/court/CourtEmailFactoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/probation/ProbationEmailFactoryTest.kt
Apologies this PR ballooned a little with some refactoring around use of users in the unit tests.
Essentially the core change prevents prison users from creating bookings not in their current active caseload.
=> BAVL-280 restrict access to create bookings for prison users enforced by their active caseload.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/EmailConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/court/CourtEmailFactory.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/court/CourtEmails.kt, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/EmailTemplatesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/SqsIntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/VideoLinkBookingIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacadeTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/GovNotifyEmailServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/court/CourtEmailFactoryTest.kt
This change adds another email to be sent to the court contact when a booking is amended by a prison user (in A&A).
=> BAVL-306 court email for court contact when booking amended by a prison user.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/EmailConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/court/CourtEmailFactory.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/court/CourtEmails.kt, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/EmailTemplatesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/VideoLinkBookingIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacadeTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/GovNotifyEmailServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/court/CourtEmailFactoryTest.kt
This change adds another email to be sent to the court contact when a booking is cancelled by a prison user (in A&A).
=> BAVL-306 court email for court contact when booking cancelled by a prison user.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacade.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacadeTest.kt
Rather than change DB just changed the actual comments going in to the notification table.  Personally I think this is fine with the reduced data.
=> BAVL-308 reason field size was being exceeded so reduced the length of the reasons provided.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/manageusers/ManageUsersClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/UserService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/ModelFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/Users.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/wiremock/ManageUsersApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/UserServiceTest.kt
This change extends the UserService to check an external users groups in terms of accessing court and probation bookings.
Further changes will be needed to excercise this.  Doing in parts so can rollback if any side effects of the change become apparent when merged/deployed in dev.
=> BAVL-310 this is the first change towards suppoting the checking of a users ability to access court and probation bookings.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AmendVideoBookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CancelVideoBookingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AmendVideoBookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CancelVideoBookingServiceTest.kt
Adding in belt and braces for cancel and amends for external users.
Only external court users can amend/cancel court bookings and external probation users amend/cancel probation bookings.
=> BAVL-310 adding check to amend and cancel bookings to ensure external user has permissions to do it.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/VideoBooking.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/AmendVideoBookingRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/CreateVideoBookingRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AmendVideoBookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingHistoryService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/ModelFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/VideoLinkBookingIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AmendVideoBookingServiceTest.kt
Removing the court code and probation team attributes from the amend journey.
Because the attributes were marked as optional on the amend request object, removal of them should not impact the UI's calling this endpoint 🤞
=> BAVL-317 prevent changing of court and probation team, attributes are not updatable once created.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/migration/MigrationClient.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/wiremock/LocationsInsidePrisonApiMockServer.kt
End to end testing revealed the URL for getting a location by its ID wasn't quite right.
=> BAVL-342 correcting URL to locations API.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/migration/MigrationClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/migration/MigrateMappingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/migration/MigrateVideoBookingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/migration/MigrateVideoBookingServiceTest.kt
A trial migration raised a couple of issues:
- `other` court codes
- `comments` too long for booking history
=> BAVL-43 handle OTHER court code and trim history comments to 1000 characters.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/VideoLinkBookingsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/mapping/VideoLinkBookingMappers.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/EntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/VideoLinkBookingsServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/mapping/VideoLinkBookingMappersTest.kt
When a migrated booking has a free text description for the court or probation team this needs to be carried through to callers of the API e.g. front end.
Previously this would just have had a description of 'uknown'.
=> BAVL-371 carry through the migrated description if present (to the UI) for migrated bookings.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/security/VideoBookingAccess.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/EntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/security/VideoBookingAccessKtTest.kt
After running a migration it became apparent by tweaking the URL when viewing a booking external users can see UNKNOWN bookings made by prison users.  This change now prevents that from happening.
=> BAVL-372 external users can no longer see UNKNOWN courts/probation bookings created by prison users.

src/main/resources/migrations/common/V2024.10.15__extra_prisons.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/PrisonsResourceIntegrationTest.kt
Details on ticket - missing prisons, at least one of which (Peterborough) was blocking the migration of existing bookings.
=> BAVL-380: Adding missing prisons

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacade.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/CourtBookingAmendedTelemetryEvent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/CourtBookingCancelledTelemetryEvent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/CourtBookingCreatedTelemetryEvent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/ProbationBookingAmendedTelemetryEvent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/ProbationBookingCancelledTelemetryEvent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/ProbationBookingCreatedTelemetryEvent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/TelemetryService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacadeTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/CourtBookingAmendedTelemetryEventTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/CourtBookingCancelledTelemetryEventTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/ProbationBookingAmendedTelemetryEventTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/ProbationBookingCancelledTelemetryEventTest.kt
This change introduces two new metrics for Court and probation cancellations.
There is also a bit of refactoring that has taken place as a result of introducing them.
=> BAVL-260 capturing metrics for cancellation of court and probation bookings.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/repository/VideoBookingRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/PrisonerMergedEventHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/PrisonerMergedTelemetryEvent.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/InboundEventsIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/PrisonerMergedEventHandlerTest.kt, src/test/resources/integration-test-data/seed-prisoner-merge.sql
Changes to support the capture of metrics for prisoner merge events.
=> BAVL-261 capturing metrics for prisoner merge events.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/ProbationBookingCancelledTelemetryEvent.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/CourtBookingCancelledTelemetryEventTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/ProbationBookingCancelledTelemetryEventTest.kt
Noticed during testing in dev the metric name/label was not quite right for the probation cancellations.
=> BAVL-260 correcting the event type for probation cancellations, tests updated.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/resource/MigrationController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/migration/MigrateVideoBookingService.kt
Improving telemetry failure logging around offender booking id not found.
Also added a temporary migration controller so we can migrate an individual booking on a need only basis e.g. something fails to migrate but we can easily retry it.
=> BAVL-43 slight improvement to logging and adding temporary migration controller to assist with debugging.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/repository/VideoAppointmentRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/resource/VideoLinkBookingController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacade.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingHistoryService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/DomainEvents.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/InboundEventsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/PrisonerVideoAppointmentCancelledEventHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/CourtBookingCancelledTelemetryEvent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/ProbationBookingCancelledTelemetryEvent.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/TestEmailConfiguration.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/EntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/InboundEventsIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/JobTriggerIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/VideoLinkBookingIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacadeTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/InboundEventsServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/PrisonerVideoAppointmentCancelledEventHandlerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/CourtBookingCancelledTelemetryEventTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/ProbationBookingCancelledTelemetryEventTest.kt, src/test/resources/integration-test-data/seed-historic-booking.sql, src/test/resources/integration-test-data/seed-prisoner-merge.sql
There is a little bit of change to some of the method signatures for cancellation, we can now be more specific with the user type.  This will help prevent accidental calling of these methods with the wrong user type.
=> BAVL-390 changes to support handling of domain event for prison appointment cancelled.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CsvDataExtractionService.kt, src/main/resources/application.yml
The CSV download was failing to download a years worth of data on migrated bookings in preprod.
Increasing the async timeout to see if this helps alleviate the issue.  Also added some progress logging for downloads.
=> BAVL-405 increase the async timeout to one minute for CSV downloads.

build.gradle.kts, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/config/FeatureSwitchesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/container/PostgresContainer.kt
If a container is already running then it will use it, if not a test container will be started.
This was bugging me a little, if I ran the tests in Intellij I had to make sure was running Postgres container manually.
=> BAVL-412 and postgres test container so can run tests without having to run docker compose file.

src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/SqsIntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/container/LocalStackContainer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/VideoLinkBookingIntegrationTest.kt, src/test/resources/application-test-localstack.yml
Instead of checking the actual queues for published messages we are waiting and checking the publisher is called instead.
This seems to be far more reliable/stable and runs every time on my local machine.
=> BAVL-413 alter approach checking for published messages so can run integration test in the CI pipeline.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CsvDataExtractionService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/CsvDataExtractionIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/wiremock/LocationsInsidePrisonApiMockServer.kt
Replace original (buggy) cache approach with the genuine Spring cache.
=> BAVL-450 peek is an intermediate operation and should not be used for population, predominantly for debug.

src/main/resources/application.yml, src/main/resources/migrations/prod/V2024.12.02__uncancel-hmp-gartree-bookings.sql
Before we synced data from Whereabouts, the A&A team did a data fix where they accidentally cancelled some appointments at Gartree, and they reverted that delete [here](https://github.com/ministryofjustice/hmpps-activities-management-api/blob/main/src/main/resources/migrations/prod/V2024.10.31__gartree_appts_undelete.sql)
The trouble is, they did not also fix the data in Whereabouts, so we have migrated across the bad data. We are fixing the bad data here post-migration
=> BAVL-463: Fix some data where Gartree bookings are not synced with nomis

helm_deploy/values-dev.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/TimeSourceConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacade.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/jobs/CourtHearingLinkReminderJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/jobs/JobRunner.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/jobs/Jobs.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/JobTriggerIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/jobs/CourtHearingLinkReminderJobTest.kt
Reminder emails sent Monday to Thurs and Sunday look a day ahead.
Reminder emails sent Friday look at the following Monday.
Reminder emails are not sent on Saturday.
=> BAVL-501 adding a bit more logic around what days reminder emails are sent and how far in the future to look.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/VideoAppointment.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AvailabilityFinderService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/JobTriggerIntegrationTest.kt
Behavior should be the same as a result of this PR i.e. we are still only looking locally for clashing appointments.
Following PR will combine with appointment data not mastered in BVLS.
=> BAVL-522 preparation PR for the clashing appointments fix. Pulling out common interface in availability check to combine data from multiple sources.

helm_deploy/hmpps-book-a-video-link-api/values.yaml, helm_deploy/values-dev.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/prisonapi/PrisonApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/VideoAppointment.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/resource/AvailabilityController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AvailabilityService.kt, src/main/resources/application-local.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AvailabilityServiceTest.kt
Changes to support booking/appointment clashes in both BVLS and externally e.g. NOMIS.
This feature is only enabled in DEV, will fall back to original process in other environments.
=> BAVL-522 changes to support clashing checks with bookings in BVLS and external appointments. This sits behind a feature toggle.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/repository/VideoBookingEventRepository.kt
Use timestamp (AKA creation timestamp) instead of date_booked for query.
date_booked would be the same for all events for a booking even if they occurred on different days.
=> BAVL-522 using timestamp instead of date_booked (date_booked is the same for all events related to a booking).

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AppointmentsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacade.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/VideoLinkBookingIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AmendVideoBookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateVideoBookingServiceTest.kt
We need to go back to this and add the clashing checking to the facade.
This change is safe in the short term as the UI performs an availability check prior to create or amend.
=> BAVL-534 temporarily removes the clashing booking check, as the availability check is called first in the UI.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/resource/VideoLinkBookingController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AvailabilityService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacade.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/RequestBookingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/ModelFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/VideoLinkBookingIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AmendVideoBookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AvailabilityServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacadeTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateVideoBookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/RequestBookingServiceTest.kt
This change replaces what was temporarily removed, a check of clashing prison appointment times (in BVLS only).
**Note this does go further and checks external clashes as well. Do we want to switch the external check off in these cases?**
=> BAVL-534 this changes adds the availability check to the core API end points, create, amend and request a booking.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/ManageExternalAppointmentsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/ManageExternalAppointmentsServiceTest.kt
The original intention of prefixing comments was so prison users could see information about court/probation meetings in other areas where this information would not be visible e.g. NOMIS, 7 day schedule etc.
This does however cause confusion as this is not something that has been entered by the user that created or amended a bookings comments.
=> BAVL-571 do not automatically add extra information to a bookings comments, only users should be adding/changing comments.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/activitiesappointments/ActivitiesAppointmentsClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/ManageExternalAppointmentsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/activitiesappointments/ActivitiesAppointmentsClientTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/ManageExternalAppointmentsServiceTest.kt
When bookings are amended the existing correlating A&A appointments should be deleted on cancel.  New appointments will replace them.
When bookings are cancelled the existing correlating A&A appointments should not be deleted on cancel.  There are no new appointments to replace them.
=> BAVL-599 support soft and hard delete of A&A appointments for amend and cancel operations via BLVS.

.gitignore, docker-compose-localstack.yml, helm_deploy/hmpps-book-a-video-link-api/values.yaml, run-localstack.sh, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/activitiesappointments/ActivitiesAndAppointmentsExt.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/activitiesappointments/ActivitiesAppointmentsClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/prisonapi/PrisonApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/common/AppointmentType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/common/SupportedAppointmentTypes.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/FeatureSwitches.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/BookingHistory.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/BookingType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/PrisonAppointment.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AvailabilityService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/DomainEvents.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/ManageExternalAppointmentsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/PrisonerVideoAppointmentCancelledEventHandler.kt, src/main/resources/application-local.yml, src/main/resources/application-localstack.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/activitiesappointments/ActivitiesAppointmentsClientTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/prisonapi/PrisonApiClientTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/common/SupportedAppointmentTypesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/config/FeatureSwitchesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/wiremock/ActivitiesAppointmentsApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/wiremock/PrisonApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/ManageExternalAppointmentsServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/PrisonerVideoAppointmentCancelledEventHandlerTest.kt
This change introduces support for the dedicated probation meeting type (which ultimately ends up in NOMIS after sync).
The change is feature toggled so by default it is switched off.
Included in this PR is adding support for running locally with Localstack, this enabled me to see the events being raised and consumed and ultimately sent to both prison-api and activities and appointments.
=> BAVL-428 feature toggled support for the probation meeting type VLPM.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/Location.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/LocationsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/mapping/LocationMappers.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/LocationsServiceTest.kt
Minor changes only:
* Return the IDs for attributes and schedules on room decorations
* Return enabled locations (from locations api) even it the room decoration shows INACTIVE so they are visible on the admin forms.
=> BAVL-600: Add ids to responses and return INACTIVE locations in decorations

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/common/StringExt.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/AdditionalBookingDetail.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/repository/AdditionalBookingDetailRepository.kt, src/main/resources/migrations/common/V2025.02.07__additional_booking_detail.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/common/StringExtensionUtilsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/AdditionalBookingDetailTest.kt
Initial attempt to provide an entity to capture additional booking details primarily for the new probation journey.
This is not tied to the probation journey specifically so can be used for other booking types should the need arise.
Needs wiring into the various endpoints e.g. create and backend services.
We will also need a means to record changes to booking details e.g. history.
=> BAVL-611 new entity to support the capture of additional booking details (for the updated probation journey).

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/AdditionalBookingDetail.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/AdditionalBookingDetails.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/CreateVideoBookingRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacade.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateProbationBookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/VideoBookingServiceDelegate.kt, src/main/resources/migrations/dev/V2025.02.11__reference_data.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/common/StringExtensionUtilsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/AdditionalBookingDetailTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/ModelFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/ProbationBookingIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/ReferenceCodesResourceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/wiremock/NomisMappingApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/wiremock/PrisonApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/AdditionalBookingDetailsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacadeTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateProbationBookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/VideoBookingServiceDelegateTest.kt
Changes to support the new probation journey attributes for the create journey.
Will be doing the amend journey next.
Note the feature toggle is still off so this is safe to merge.  I have not changed the existing creation process (bar the request object).
=> BAVL-616 initial PR to support dedicated probation journey creation with new attributes.

src/main/resources/migrations/common/V2025.02.18.1__add_isleworth_crown_probation.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/ProbationTeamsResourceIntegrationTest.kt
The primary contact will be added manually, separately to this.
Details on Confluence pages.
=> BAVL-630: Add Isleworth Crown - Probation (ISLWCP) team to the PPoC teams

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/prisonapi/PrisonApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AvailableLocationsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookedLocationsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/ModelFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AvailableLocationsServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookedLocationsServiceTest.kt
This change allows for the amend journey where we still want to see the times in the allowable slots for the existing journeys appointments prior to changing it.
=> BAVL-628 change to factor in existing booking. If one is supplied then results will still show the existing bookings time as available in the results.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/common/CollectionExt.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/common/LocalTimeExt.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/LocationAttribute.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/LocationSchedule.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AvailableLocationsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/LocationAttributesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AvailableLocationsServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/LocationAttributesAvailableServiceTest.kt
Refactoring so we can work with an actual status from the location attribute as opposed to a boolean value.  This is in preparation for supporting schedules where boolean on its own isn't sufficient.  For example for probation a schedule could be shared, probation, probation team.
=> BAVL-628 refactoring

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/nomismapping/NomisMappingClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/CacheConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/locations/availability/AvailableLocationsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/locations/availability/BookedLocationsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/locations/availability/AvailableLocationsServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/locations/availability/BookedLocationsServiceTest.kt
This replaces multiple single GET requests to the NOMIS mapping service with a single POST call now that a bulk lookup endpoint is available on the NOMIS mapping service.
=> BAVL-676 using bulk nomis mapping location lookup endpoint now that it is available in favour of multiple single calls.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacade.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacadeTest.kt
Use the prison code off the booking and not the prisoner when prepping prison contacts for sending emails.  This is because the prison code may be something not recognised e.g. 'TRN' or 'OUT'.
We could use the last prison ID.  But if feels like we should be taking it off the booking as this should be where the email is sent.
=> BAVL-691 fix issue where by a transfer event fails when attempting to send email due to using the wrong prison code 'TRN' looking up the prison.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/VideoBooking.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateProbationBookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/ProbationTeamsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/mapping/ProbationTeamMappers.kt, src/main/resources/migrations/common/V2025.03.19__insert_probation_team_not_listed.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/VideoBookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/EntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/ProbationTeams.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/ProbationBookingIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/ProbationTeamsResourceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateProbationBookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/ProbationTeamsServiceTest.kt
This change introduces a 'Team not listed' probation team to support creation of probation booking by prison users.
'Team not listed' will be available as a team option (at the bottom of the team choices) in A&A and DPS add appointment for probation booking creation.
=> BAVL-696 adding support for 'Team not listed' for prison users when creating probation bookings.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/VideoBooking.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateProbationBookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateVideoBookingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/VideoBookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/EntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/ProbationBookingIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingHistoryServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateProbationBookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/mapping/VideoLinkBookingMappersTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/ProbationBookingAmendedTelemetryEventTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/ProbationBookingCancelledTelemetryEventTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/ProbationBookingCreatedTelemetryEventTest.kt
The CSV would have been wrong as a result of this bug.  Note: this does not affect the old journeys, only the new.
=> BAVL-696 fixing bug with prison users in new probabtion journey, not setting created by prison correctly.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/LocationAttribute.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/LocationSchedule.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/LocationAttributesTest.kt
Relax adding a schedule row to a location attribute.  Can add even if the location attribute is not scheduled.  The schedule row(s) will have no effect on room selection.
=> BAVL-663 you can now add a schedule row to a location attribute even if the location attribute is not scheduled. It will have no effect.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacade.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/probation/ProbationEmailFactory.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/probation/ProbationEmails.kt, src/main/resources/application-dev.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacadeTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/GovNotifyEmailServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/probation/ProbationEmailFactoryTest.kt
Note for these changes you will only see the new email in DEV.
I have tested this locally, so fingers crossed will work in dev also.
=> BAVL-721 changes to include new probation values in the new prison probation booking email (isolated to dev only).

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/locations/availability/TimeSlotAvailabilityService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/locations/availability/TimeSlotAvailabilityServiceTest.kt
Meeting end times cannot go beyond the end of the prison working day.
When prompting suggested available times the end time must be before or at the end of the working day.
=> BAVL-732 suggested meeting end times should not go beyond the end of the prison working day 18:00.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/court/CourtEmailFactory.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/court/CourtEmails.kt, src/main/resources/application-dev.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacadeTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/GovNotifyEmailServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/court/DeprecatedCourtEmailFactoryTest.kt
If no PVL link then nothing is shown in the email template.  The label text is provided by the API.  A bit on the fence with this idea (it was my idea).
=> BAVL-717 including pre and post PVL's in new court booking user email.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/EmailConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/probation/ProbationEmailFactory.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/probation/ProbationEmails.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/ProbationBookingCreatedTelemetryEvent.kt, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/EmailTemplatesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/EntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacadeTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/GovNotifyEmailServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/court/CourtEmailFactoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/probation/ProbationEmailFactoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/ProbationBookingCreatedTelemetryEventTest.kt
Spotted an email was missing from the new probation journey.
Prisons can now also create probation bookings, if they do then we need to send an email to the relevant probation contacts set up.
It is safe for this to change go live.  The current service does not allow probation teams to create probation bookings.
=> BAVL-734 send email to probation team when a prison creates a probation booking.

src/main/resources/migrations/common/V2025.03.31__correct_court_hypens.sql
This PR makes some of the court descriptions better match the user's expectations.
FRC-xxxx - had no spaces around hyphens.
RCJ -xxxx - one court had an elongated hyphen (odd character).
RCU-xxx - no discernable problem, but updated in case there was a ctrl character copied from Emma spreadsheet.
=> BAVL-736: Update court descriptions to expected values where hyphens exists.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/VideoBookingAmendedEventHandler.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/VideoBookingAmendedEventHandlerTest.kt
Reverts ministryofjustice/hmpps-book-a-video-link-api#446
=> Revert "BAVL-743 temporary workaround for migrating future VLB probation bookings to future VLPM bookings."

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/probation/ProbationEmailFactory.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/probation/ProbationEmails.kt, src/main/resources/application-dev.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacadeTest.kt
Adds the probation officers details and PVL to the probation cancellation emails (in DEV only).
=> BAVL-713 adding additional details and PVL to the probation cancellation emails.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/DateTimeAvailabilityRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/locations/availability/DateTimeAvailabilityService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/locations/availability/DateTimeAvailabilityServiceTest.kt
This is a backwards compatible change in that the UI will continue to work (as before) if the API were to be released without making any changes to the UI.
=> BAVL-763 show previously selected location(s) for court bookings if the date and times have not changed on amend journey.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/prisonersearch/PrisonerSearchClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/DomainEvents.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/InboundEventsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/PrisonerAppointmentsChangedEventHandler.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/ModelFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/InboundEventsIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/wiremock/PrisonerSearchApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/InboundEventsServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/PrisonerAppointmentsChangedEventHandlerTest.kt
There is no cloud platform configuration for this event at time of writing.  Until we push that out this event code will never fire.
There has been no change to the existing release event at the moment i.e. it will still operate as before.
=> BAVL-752 initial commit for supporting the appointments changed event for release and transfer of prisoners.

applicationinsights.json, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/InboundEventsListener.kt
`WithSpan` is no longer needed as this is now managed automatically by the SQS library.
The insights config has been updated on the back of a recommendation in the release note readme [here](https://github.com/ministryofjustice/hmpps-spring-boot-sqs/blob/b282d3e5db11f23948537bce0488f68710b6f4ea/release-notes/5.x.md#510)
=> BAVL-756 update SQS listener on back of recommended changes in the shared SQS library.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/common/LocalTimeExt.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/LocationAttribute.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/LocationSchedule.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/locations/availability/DateTimeAvailabilityService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/locations/availability/LocationAttributesAvailableService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/locations/availability/TimeSlotAvailabilityService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/LocationAttributesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/LocationScheduleTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/locations/availability/DateTimeAvailabilityServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/locations/availability/LocationAttributesAvailableServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/locations/availability/TimeSlotAvailabilityServiceTest.kt
Details are on the JIRA BAVL-742.
This branch now encompasses another ticket JIRA BAVL-776.  This prevents end times bleeding over their allotted slots.  For example if a slot is for 10-12 then all start and end times must be within that slot.
=> BAVL-742: Relaxes BLOCKED schedules so bookings can overlap at the exact time of the schedule boundary 

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/locations/availability/BookedLocationsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/locations/availability/BookedLocationsServiceTest.kt
This PR:
* Ignores cancelled appointments returned from A&A appointments search when checking whether a room is available.
* Wrote a failing test first - which failed - then implemented the change to make the test pass.
=> BAVL-778: Ignore cancelled appointments from A&A which were blocking rooms.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/prisonapi/PrisonApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/locations/availability/AvailabilityService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/locations/availability/BookedLocationsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/wiremock/PrisonApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/locations/availability/BookedLocationsServiceTest.kt
This PR:
* Retrieves and extra eventStatus field from Prison API for appointments at locations
* Ignores appointments that are cancelled (eventStatus=CANC) in the list
* Does not block rooms where cancelled appointments exist
=> BAVL-778: Availability check to take account of cancelled appointments via Prison API

helm_deploy/hmpps-book-a-video-link-api/values.yaml
Helm config change to enable the probation reminder email job in production.
=> BAVL-754 enable the probation details reminder email in production.

src/main/resources/migrations/common/V2025.04.28__enable_hmp_chelmsford.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/PrisonsResourceIntegrationTest.kt
The details of the manual steps are on the ticket BAVL-801 
i.e.
* Manual setting up of the feature-toggles secret for FEATURE_GREY_RELEASE_PRISONS
* Manual creation of the prison_contact rows in PREPROD and PROD.
=> BAVL-801: Enable HMP Cheltenham - initially as a grey-release prison

helm_deploy/hmpps-book-a-video-link-api/values.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/common/SupportedAppointmentTypes.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/FeatureSwitches.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AmendCourtBookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AmendProbationBookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CancelVideoBookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateCourtBookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateProbationBookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/VideoBookingServiceDelegate.kt, src/main/resources/application-local.yml, src/main/resources/application-localstack.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/common/SupportedAppointmentTypesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/config/FeatureSwitchesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/ProbationBookingIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/ScheduleResourceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/VideoLinkBookingIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AmendCourtBookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateCourtBookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/VideoBookingServiceDelegateTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/ActivitiesAndAppointmentsServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/PrisonServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/PrisonerVideoAppointmentCancelledEventHandlerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/locations/availability/BookedLocationsServiceTest.kt
Note the tests removed in the PR are now redundant and no longer needed.  They would have been related to the toggle being off and still using the old code/path which has now been removed
=> BAVL-812 removing the master VLPM appointments feature toggle, now safe to remove.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/prisonapi/PrisonApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/ManageExternalAppointmentsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/VideoBookingAmendedEventHandler.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/ManageExternalAppointmentsServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/VideoBookingAmendedEventHandlerTest.kt
This fix is for non-rolled out prisons only (A&A needs further checking to see if it is a problem).
This change resolves an issue where synced appointments were being lost if the amended appointment times overlapped the old ones.  This would only be an issue for court bookings that have at least two appointments.
Essentially this change ensures all historic appointments are removed from prison-api (NOMIS) before the creation of new (amended) ones.
=> BAVL-842 resolve issue for non-rolled out prisons where overlapping synced appointments are lost on amendening.

src/main/resources/migrations/common/V2025.05.15__add_northwest_courts.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/CourtsResourceIntegrationTest.kt
This is a bit fiddly - and needs verification on DEV and PREPROD, but I've tested locally and looks fine here.
I have a separate script to run manually which will add the contact email addresses for each of the new courts - does not go into Github.
=> BAVL-810: Adding North West courts into BVLS

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AmendCourtBookingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/EntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/ModelFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/VideoLinkBookingIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AmendCourtBookingServiceTest.kt
This change is to ensure existing comments or notes are not accidentally lost when the feature toggle is switch on/off.
=> BAVL-849 ensure existing comments/notes are maintained when toggle is on/off.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/VideoBookingEvent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CsvDataExtractionService.kt, src/main/resources/migrations/common/R__v_video_booking_event.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/CsvDataExtractionIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CsvDataExtractionServiceTest.kt, src/test/resources/integration-test-data/seed-court-events-by-hearing-date-data-extract.sql, src/test/resources/integration-test-data/seed-events-by-booking-date-data-extract.sql
This changes includes the CVP link (video URL) if there is one (or nothing if not) in both court CSV extracts by booking date and by hearing date.
=> BAVL-924 this change adds the video URL (CVP link) to court CSV extracts in the final column of the CSV files.

utility/disable-bvls-hmcts-link-guest-pin.sh, utility/enable-bvls-hmcts-link-guest-pin.sh
The daily schedule service also needs restarting when the FEATURE_HMCTS_LINK_GUEST_PIN is changed.  It does not need its own file, it can piggy back on existing disable and enable scripts because the toggle name is shared across services.
=> BAVL-915 adding the daily schedule to the list of deployments that needs restarting when the FEATURE_HMCTS_LINK_GUEST_PIN is changed.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/resource/VideoLinkBookingController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacade.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/VideoBookingServiceDelegate.kt, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/ModelFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/VideoBookingServiceDelegateTest.kt
This change brings the API inline with A&A appointment validation which prevents bookings from being too far into the future.
Given this is an edge case and we have only seen this happen once we have chosen the path of least resistance here and just put the enforcement in the API only and not the UI's. Doing in the UI's as well would require 3 services to be changed.
What users will see in the UI when they try and save:
=> BAVL-975 bring the service inline with A&A for the maxixmum days into the future a booking (appointent) can be.

helm_deploy/values-dev.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/administration/AdministrationEmailService.kt, utility/add-admin-emails.sh
Setting up API to read dev namespace env vars for admin emails job for manual testing of job in dev.
The cron to run the job is not yet needed.
=> BAVL-1001 add admin emails for dev namespace for manual testing of job (no cron in place yet).

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/administration/AdministrationEmailService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/administration/AdministrationEmailServiceTest.kt
This change fixes a bug whereby prisons with no new rooms were also being included in the email that is sent.
=> BAVL-1001 bug fix

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/resource/CsvDataExtractionController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CsvDataExtractionService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/CsvDataExtractionIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CsvDataExtractionServiceTest.kt, src/test/resources/integration-test-data/seed-BMI-decorated-locations.sql
This PR:
* Adds an endpoint which is called via the Admin tiles of the UI to get a CSV data download.
* Extracts all active prison VIDE locations and their room decoration data
* Formats the data (repeating schedule rows for each room set to type SCHEDULE)
* Formats the schedule data into one string which describes the rules.
=> BAVL-1010: Endpoint to provide room configuration data as CSV extract

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/VideoBookingEvent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CsvDataExtractionService.kt, src/main/resources/migrations/common/R__v_video_booking_event.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/CsvDataExtractionIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CsvDataExtractionServiceTest.kt, src/test/resources/integration-test-data/seed-probation-events-by-meeting-date-data.sql
This changes adds the probation officer name and email to the probation CSV extracts when present.
When not present for a booking then "Not known" will be shown instead.
=> BAVL-1023 adds the probation officer name and email address where present to the probation CSV extracts.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/activitiesappointments/ActivitiesAppointmentsClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/ActivitiesAndAppointmentsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/ProbationBookingIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/ActivitiesAndAppointmentsServiceTest.kt
The purpose of this change is move towards using DPS location IDs instead of NOMIS locations IDs when patching appointments via the A&A API (now that A&A supports DPS location IDs).
This only changes the patch of appointments.  Search will be coming next.
=> BAVL-1026 changing patch appointment call to A&A to use DPS location ID instead of the NOMIS location ID.

src/main/resources/migrations/common/V2025.08.22__new_probation_teams.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/ProbationTeamsResourceIntegrationTest.kt
This adds 19 new probation teams, into all environments.
Once there I will also add the team contacts emails, but only in PREPROD and PROD - and this step is done manually to avoid any email addresses being checked-into GitHub.
=> BAVL-1017: Adding 19 new probation teams

.github/workflows/security_owasp.yml, .github/workflows/security_trivy.yml, .github/workflows/security_veracode_pipeline_scan.yml, .github/workflows/security_veracode_policy_scan.yml, build.gradle.kts
The aim is to get the overnight Github actions security scans working with the v2 NVD feed. 
The DEV CP namespace has had its GH terraform integrations updated from v5.39.0 to v6.6.0.
=> BAVL-1058: Update gradle springboot plugin to v9.0.0 and GH workflows
