- build.gradle.kts
- src/main/resources/application-local.yml
- src/main/resources/application.yml
- src/main/resources/migrations/common/V2024.04.22__baseline_tables.sql
- src/main/resources/migrations/common/V2024.04.23__baseline_data.sql
- src/test/resources/application-test.yml
Initial data model and base data.
No location decoration or default CVP / PCVL links  yet.
Keeping simple for now so that migration in from current BVL data is easier.
> BAVL-7: Flyway configured, initial data model and base data added.

- helm_deploy/hmpps-book-a-video-link-api/values.yaml
- run-local.sh
- src/main/resources/application.yml
Introduce DB parameters from secrets.
Set DB SSL mode from environment.
> BAVL-8: Setup DB properties from namespace secrets

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/EmailConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/GovNotifyEmailService.kt
This is the initial commit to get the basic configuration in place to support the sending of the various emails needed by the service.
There is still a bit more work to be done.
> BAVL-14 work in progress commit to support the sending of emails in the service.

- helm_deploy/hmpps-book-a-video-link-api/values.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/EmailConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/GovNotifyEmailService.kt
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/health/Assertions.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CourtNewBookingEmailTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/GovNotifyEmailServiceTest.kt
This change strips some of the previous work back a little to focus more on a specific journey.  In this case the court booking a new video appointment.
> BAVL-14 add the new court booking template config and associated email.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/activitiesappointments/ActivitiesAppointmentsClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/locationsinsideprison/LocationsInsidePrisonClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/prisonersearch/PrisonerSearchClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/Court.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/ProbationTeam.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/VideoBooking.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/CreateVideoBookingRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/repository/CourtRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/repository/ProbationTeamRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/repository/VideoBookingRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/resource/VideoLinkBookingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateVideoBookingService.kt
- src/main/resources/migrations/common/V2024.04.22__baseline_tables.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/prisonersearch/PrisonerSearchClientTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/Assertions.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/EntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/ModelFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/CreateVideoBookingRequestTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateVideoBookingServiceTest.kt
The work in progress for this PR now goes a stage further to start creating the video bookings in the service layer.  This is still pretty basic.
I will soon start adding basic controller and integration tests so we have some real end to end testing going on.
> BAVL-98 initial first attempt at the beginnings of entity modelling for the create a booking journey.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/common/LocalTimeExt.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/common/LocalTimeUtils.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/HmppsBookAVideoLinkApiExceptionHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/repository/PrisonAppointmentRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/resource/VideoLinkBookingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateVideoBookingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/common/LocalTimeUtilsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/DateTimeSource.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/ModelFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/Prisons.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/VideoLinkBookingIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateVideoBookingServiceTest.kt
- src/test/resources/test_data/clean-all-data.sql
These change prevent the creation of overlapping booking appointments with existing appointments.
> BAVL-98 changes to prevent overlapping appointments from being created.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/WebClientConfiguration.kt
So tried this locally and worked so should work in dev also.
Using single builder bean was the issue.
> BAVL-98 changes to web client config to not use a shared builder.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/BvlsRequestContextConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/resource/VideoLinkBookingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateVideoBookingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/BvlsRequestContextConfigurationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/VideoLinkBookingIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateVideoBookingServiceTest.kt
Changes to support capture of the username (or client_id) on requests to the service so we can keep a record of who did what.
> BAVL-98 these changes to support capture of user context/details on requests to the service.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/locationsinsideprison/LocationsInsidePrisonClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/locationsinsideprison/extensions/LocationExt.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/prisonersearch/PrisonerSearchClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/PrisonAppointment.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateVideoBookingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/locationsinsideprison/LocationValidatorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/locationsinsideprison/LocationsInsidePrisonClientTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/prisonersearch/PrisonerSearchClientTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/prisonersearch/PrisonerValidatorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/ModelFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/Prisons.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/VideoLinkBookingIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/wiremock/LocationsInsidePrisonApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateVideoBookingServiceTest.kt
These changes now mean to create a booking you'll need to use a valid location key.
This will mean the prison code will also need match that in the location key e.g. `prison code = ABC` and `location key = ABC-1-23456`
> BAVL-123 changes to check the location for a booking is a valid location at a given prison.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/BookingContact.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/BookingContact.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/repository/BookingContactsRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/resource/BookingContactsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingContactsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/mapping/BookingContactMappers.kt
- src/main/resources/migrations/common/R__v_booking_contacts.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/ModelFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/Prisons.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/BookingContactsResourceIntegrationTest.kt
Contact types are:
PRISON
PROBATION
COURT
THIRD_PARTY
And each contains the type, name, email, telephone and position (or organisation).
> BAVL-129: Implements a view, repository, service and endpoint to retrieve the contact details related to a booking

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/common/LocalDateExt.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/common/LocalTimeExt.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/EmailConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/Prison.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/GovNotifyEmailService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/EntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/ModelFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/VideoLinkBookingIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacadeTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CourtNewBookingEmailTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/GovNotifyEmailServiceTest.kt
- src/test/resources/test_data/clean-all-data.sql
This is only sending one email at the moment.
It is also recording successful emails sent in the notifications audit trail table.
> BAVL-123 intial attempt at wiring in call to email service for sending a court email. Still more work to be done.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/HmppsBookAVideoLinkApiExceptionHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/CreateVideoBookingRequest.kt
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/DateTimeSource.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/CreateVideoBookingRequestTest.kt
Constraint violations will now show as:
> BAVL-166 changes to appointment date and time validation to allow future appointments to start with todays date.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/common/LocalTimeExt.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacade.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/common/LocalTimeExtTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/ModelFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacadeTest.kt
You can see the room name and times are as they should be ...
> BAVL-174 including rooms names and removing seconds from times in appointments on emails sent.

- build.gradle.kts
- helm_deploy/hmpps-book-a-video-link-api/values.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/InboundEventsListener.kt
Not 100% this is entirely correct.  May need to revert the PR if the service fails to start after merging into main.
> BAVL-25 adding config and wiring for SQS.

- build.gradle.kts
- helm_deploy/hmpps-book-a-video-link-api/values.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/InboundEventsListener.kt
Reverts ministryofjustice/hmpps-book-a-video-link-api#69
> Revert "BAVL-25 adding config and wiring for SQS."

- build.gradle.kts
- helm_deploy/hmpps-book-a-video-link-api/values.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/InboundEventsListener.kt
Reverts ministryofjustice/hmpps-book-a-video-link-api#70
> Revert "Revert "BAVL-25 adding config and wiring for SQS.""

- build.gradle.kts
- helm_deploy/hmpps-book-a-video-link-api/values.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/InboundEventsListener.kt
From reviewing code in another project I have seen a couple of other evn settings that are potentially missing.  Too be honest it is not very clear.
> BAVL-25 second attempt at adding config and wiring for SQS.

- build.gradle.kts
- helm_deploy/hmpps-book-a-video-link-api/values.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/InboundEventsListener.kt
Reverts ministryofjustice/hmpps-book-a-video-link-api#73
> Revert "BAVL-25 second attempt at adding config and wiring for SQS."

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/DomainEvents.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/InboundEventsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/AppointmentCreatedEventHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/DomainEventHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/VideoBookingCreatedEventHandler.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/InboundEventsListenerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/AppointmentCreatedDomainEventHandlerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/VideoBookingCreatedDomainEventHandlerTest.kt
No real functional changes here, removing redundant Event interface.
> BAVL-25 refactoring, removing some redundant interfacing.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/activitiesappointments/ActivitiesAppointmentsClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/prisonapi/PrisonApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingContactsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/VideoLinkBookingsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/activitiesappointments/ActivitiesAppointmentsClientTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/prisonapi/PrisonApiClientTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/wiremock/ActivitiesAppointmentsApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/wiremock/PrisonApiMockServer.kt
A further level of filtering will probably be required e.g. times.
> BAVL-25 slight update to external appointment retrieval to filter only interested locations.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/PrisonAppointment.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/VideoBooking.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/resource/VideoLinkBookingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CancelVideoBookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/DomainEvents.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/InboundEventsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/OutboundEventsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/VideoBookingCancelledEventHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/VideoBookingCreatedEventHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/mapping/VideoLinkBookingMappers.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/PrisonAppointmentTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/VideoBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/Assertions.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/VideoLinkBookingIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacadeTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CancelVideoBookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/InboundEventsServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/OutboundEventsServiceImplTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/AppointmentCreatedEventHandlerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/VideoBookingCreatedEventHandlerTest.kt
This should be mergable. It is missing emitting of cancellation event and sending of cancellation emails.
> BAVL-213 intial work in progress commit to support cancellation of video bookings.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/VideoBooking.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CancelVideoBookingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/VideoLinkBookingIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacadeTest.kt
Outstanding part is deletion of appointments from external services.  Next on my list.
Cloud platform change for the booking cancelled event.
**DO NOT MERGE UNTIL THIS** [PR](https://github.com/ministryofjustice/cloud-platform-environments/pull/23862) **IS IN**.
> BAVL-213 wiring in calls to cancellation emails and emitting (no-op) cancellation event.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/VideoBooking.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AmendVideoBookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AppointmentsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateVideoBookingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AmendVideoBookingServiceTest.kt
This was tested locally for create, multiple amendments, changing comments and cancelling.
> BAVL-199: History fix when amending video link bookings.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/DomainEvents.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/DomainEventTypeTest.kt
> BAVL-213 fixing mapping of inbound cancellation event. Mapped to incorrect event type.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/BookingHistory.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AmendVideoBookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingHistoryService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CancelVideoBookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateVideoBookingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AmendVideoBookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingHistoryServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CancelVideoBookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateVideoBookingServiceTest.kt
> BAVL-199: Recording the booking history for cancellation

- .trivyignore
- build.gradle.kts
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/VideoLinkBookingIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/VideoLinkBookingsServiceTest.kt
It's been a while since bumping 3rd dependencies and the list has been growing so doing now so it doesn't drift any further.
> BAVL-231 updating API 3rd party dependencies.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/CourtEmailFactory.kt
I'd suggest we follow a similar pattern for probation as well.
> BAVL-235 pulling out court email creation from facade into a factory.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/prisonersearch/PrisonerSearchClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/EmailConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/Prisoner.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/GovNotifyEmailService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/CourtEmailFactory.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/DomainEvents.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/OutboundEventsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/PrisonerReleasedEventHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/mapping/PrisonerMappers.kt
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/EmailTemplatesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/ModelFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacadeTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/GovNotifyEmailServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/CourtEmailFactoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/OutboundEventsServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/PrisonerReleasedEventHandlerTest.kt
Changes to support the sending of emails for release/transfer of prisoners.
> BAVL-235 initial commit for wiring in release and transfer emails for offender release events.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/VideoBookingSearchRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/repository/VideoAppointmentRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/resource/VideoLinkBookingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/ContactsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/VideoLinkBookingsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/EntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/VideoLinkBookingIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/VideoLinkBookingsServiceTest.kt
- src/test/resources/integration-test-data/seed-search-for-booking.sql
The change adds a new endpoint to search for a single matching booking for the given search criteria.
> BAVL-263 intial commit adding search support for video bookings.

- .circleci/config.yml
- Dockerfile
- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
- gradlew.bat
Update bumps the Circle CI ORB, JARs and Gradle wrapper.
I have tested this by running the security job on the pipeline and it goes green.
> BAVL-307 OWASP security updates.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateVideoBookingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/VideoLinkBookingIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AmendVideoBookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateVideoBookingServiceTest.kt
Only prison and court users can create court bookings.
Only probation users can create probation bookings.
> BAVL-310 adding check to create bookings to ensure only specific user types can create them.

- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/Users.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/AvailabilityResourceIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/BookingContactsResourceIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/CourtsResourceIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/InboundEventsIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/ProbationTeamsResourceIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/ScheduleResourceIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/VideoLinkBookingIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/wiremock/ManageUsersApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/resource/VideoLinkBookingControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/security/CaseloadAccessKtTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AmendVideoBookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingHistoryServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CancelVideoBookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateVideoBookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/VideoLinkBookingsServiceTest.kt
Refactoring tests, removing all references to EXTERNAL_USER and replacing with usecase specific users e.g. COURT_USER/PROBATION_USER.
> BAVL-310 refactoring, removing all references to EXTERNAL_USER in tests.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/Court.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/ProbationTeam.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/migration/MigrateVideoBookingService.kt
- src/main/resources/migrations/common/V2024.04.23__baseline_data.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/CourtsResourceIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/MigrateBookingIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/ProbationTeamsResourceIntegrationTest.kt
Adds support to the migration process to deal with uknown courts and/or probation teams.
> BAVL-342 changes to handle unknown courts and probation teams.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/MigrateVideoBookingEventHandler.kt
Easier to change our side instead of whereabouts ...
> BAVL-342 the event details don't match up with that of the event raised by whereabouts.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/TelemetryService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/MigrateVideoBookingEventHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/jobs/JobRunner.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/TelemetryServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/MigrateVideoBookingEventHandlerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/jobs/JobRunnerTest.kt
A refactoring exercise on the telemetry code, existing telemetry will carry on working as before.
> BAVL-258 refactoring telemetry code in preparation for adding metric based telemetry.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/common/LocalTimeExt.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/PrisonAppointment.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/VideoBooking.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AmendVideoBookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/MigrateVideoBookingEventHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/jobs/JobRunner.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/CourtBookingCreatedTelemetryEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/ProbationBookingCreatedTelemetryEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/TelemetryService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/PrisonAppointmentTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacadeTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/MigrateVideoBookingEventHandlerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/jobs/JobRunnerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/CourtBookingCreatedTelemetryEventTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/ProbationBookingCreatedTelemetryEventTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/TelemetryServiceTest.kt
This PR introduces the capturing of metrics for court and probation bookings.
> BAVL-258 capturing metrics for creation of court and probabtion bookings.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/CourtBookingAmendedTelemetryEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/ProbationBookingAmendedTelemetryEvent.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacadeTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/CourtBookingAmendedTelemetryEventTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/ProbationBookingAmendedTelemetryEventTest.kt
Adds telemetry capture for court and probation booking amendments.
> BAVL-259 capturing metrics for amendment of court and probabtion bookings.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/locationsinsideprison/LocationsInsidePrisonClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/manageusers/ManageUsersClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/migration/MigrationClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/prisonapi/PrisonApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/prisonersearch/PrisonerSearchClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/WebClientConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/health/HealthPingCheck.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/health/HealthCheckTest.kt
We were missing health checks for two dependent services, now added.
Also added some logging for the API clients.
> BAVL-414 add missing health checks for dependent services.

- helm_deploy/hmpps-book-a-video-link-api/values.yaml
- helm_deploy/values-dev.yaml
Sets checking of external appointments for room availability on in all environments.
> BAVL-522: Turn on checking of external appointments in all environments

- helm_deploy/hmpps-book-a-video-link-api/values.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/VideoBooking.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/resource/AvailabilityController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AvailabilityService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/EntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AvailabilityServiceTest.kt
I have also taken out the feature toggle.  This means the testing is going through the latest availability check function.
> BAVL-534 availbility check should pass if existing booking date, time and location has not changed.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/VideoBookingEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CsvDataExtractionService.kt
- src/main/resources/migrations/common/R__v_video_booking_event.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/CsvDataExtractionIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CsvDataExtractionServiceTest.kt
- src/test/resources/integration-test-data/seed-court-events-by-hearing-date-data-extract.sql
- src/test/resources/integration-test-data/seed-probation-events-by-meeting-date-data.sql
Additional CSV extract columns:
For court bookings - hearing type and user responsible for the event (create/update/delete).
For probation bookings - meeting type and user responsible for the event (create/update/delete).
> BAVL-525 additional columns for CSV, hearing type for court, meeting type for probation and the user.

- src/main/resources/migrations/common/R__v_video_booking_event.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/CsvDataExtractionIntegrationTest.kt
- src/test/resources/integration-test-data/seed-court-events-by-hearing-date-data-extract.sql
- src/test/resources/integration-test-data/seed-events-by-booking-date-data-extract.sql
Bug fix for meeting/hearing type join for CSV extract.
> BAVL-525 join for meeting/hearing type should have been on the booking_history table and not the video_booking table.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingHistoryService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingHistoryServiceTest.kt
Added some basic validation checks prior to creating any booking history for a video booking.
> BAVL-570 added in some simple validation to ensure booking is in correct state before recording any history.

- helm_deploy/hmpps-book-a-video-link-api/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/FeatureSwitches.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/InboundEventsListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/ManageExternalAppointmentsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/OutboundEventsPublisher.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/config/FeatureSwitchesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/InboundEventsListenerTest.kt
- src/test/resources/application-test-localstack.yml
There is no need for this toggle anymore, the service is live.  It is always on.
> BAVL-428 small refactor. Feature toggle for SNS is no longer needed.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/AmendVideoBookingRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/repository/AdditionalBookingDetailRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AmendProbationBookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/VideoBookingServiceDelegate.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/EntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/ModelFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/ProbationBookingIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/VideoLinkBookingIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AmendProbationBookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateProbationBookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/VideoBookingServiceDelegateTest.kt
- src/test/resources/integration-test-data/seed-probation-team-user-access.sql
Changes to support the new probation amend changes.
Note:
Two thirds way though this work, the goal posts moved so technically the create and amend are no longer correct.  The change in scope means additional details will be optional and not mandatory as they currently are.
I am going to do this as an independent change/PR.
> BAVL-617 initial PR to support dedicated probation journey amend with new attributes.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/AdditionalBookingDetail.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/AdditionalBookingDetails.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AmendProbationBookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateProbationBookingService.kt
- src/main/resources/migrations/common/V2025.02.14__alter_additional_booking_detail.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/AdditionalBookingDetailTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/EntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/ProbationBookingIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/AdditionalBookingDetailsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AmendProbationBookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/CreateProbationBookingServiceTest.kt
Additional details are no longer mandatory or probation bookings.
When they are provided name and email must be provided.  Contact number is optional.
> BAVL-617 additional details are not mandatory for probation bookings.

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/activitiesappointments/ActivitiesAppointmentsClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/nomismapping/NomisMappingClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/prisonapi/PrisonApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/PrisonConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/AvailableLocationsRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/BookingType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/CreateVideoBookingRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/TimeSlot.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/response/AvailableLocationsResponse.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/resource/AvailabilityController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AvailableLocationsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/AvailableLocationsRequestTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AvailableLocationsServiceTest.kt
Looks for available spaces against existing bookings/appointments.
Filters out based on chosen time slot(s)
Still to do:
Apply room decorations filtering.
> BAVL-628 endpoint for looking up available locations/rooms when making a booking,

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/PrisonConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/response/AvailableLocationsResponse.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AvailableLocationsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookedLocationsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AvailableLocationsServiceTest.kt
The change will adjust the point in time we start looking for available locations if the request is for today an we are beyond the regime start time.
E.g. 
With regime start time = 8:00AM and date = today
Adjusted start times below:
10:00AM -> 10:15
10:01AM -> 10:30
10:15AM -> 10:30
10:16AM -> 10:45
and so on ...
We may want to soften these a little e.g. 10:01 becoming 10:30 might a bit extreme.
> BAVL-628 will start looking for available locations from now going forwards for requests for today.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/response/AvailableLocationsResponse.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AvailableLocationsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AvailableLocationsServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/LocationAttributesAvailableServiceTest.kt
So the fundamental flow is in place with this PR.
There may be further work to do with regards to ordering/prioritisation of rooms.
More attention/work is still needed to the rules in the Domain for the LocationAttribute entity e.g. scheduled.
> BAVL-628 including checks for those rooms that are decorated.  The logic in the LocationAttribute entity now needs extending.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/LocationAttribute.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/LocationSchedule.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/AvailableLocationsRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/resource/AvailabilityController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AvailableLocationsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/LocationAttributesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/AvailableLocationsRequestTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AvailableLocationsServiceTest.kt
The beginnings of applying the logic with regards to ordering of the available locations with respect to the location usage.
> BAVL-628 starting to apply restrictions to location usages - WIP.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/common/CollectionExt.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AvailableLocationsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AvailableLocationsServiceTest.kt
These changes reduce the room choices based on the room decorations bar room schedules.
Schedules are still yet to be done.
> BAVL-628 applying restrictions to dedicated booking types, dedicated booking codes/teams and shared roomes. Does not include schedules.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/common/DayOfWeekExt.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/LocationAttribute.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/LocationSchedule.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AvailableLocationsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/LocationAttributesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/LocationScheduleTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AvailableLocationsServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/LocationAttributesAvailableServiceTest.kt
Changes to support room/location availability for probation location/rooms decorated with schedules.
> BAVL-628 adding logic for probabation availability with schedules.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/LocationAttribute.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/Location.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/AmendDecoratedRoomRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/CreateRoomScheduleRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/resource/RoomAdministrationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/administration/AmendDecoratedRoomService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/administration/CreateDecoratedRoomService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/mapping/LocationMappers.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/LocationAttributesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/LocationScheduleTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/EntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/ModelFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/PrisonsResourceIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/RoomAdministrationIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/VideoLinkBookingIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/AvailableLocationsServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/LocationsServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/administration/AmendDecoratedRoomServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/administration/CreateDecoratedRoomServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/administration/CreateRoomScheduleServiceTest.kt
As discussed there are some questions on the inconsistency with the naming of things.  Will address in a separate PR.
> BAVL-667 endpoint to support amending decorated rooms/locations.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/LocationAttribute.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/LocationSchedule.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/AmendRoomScheduleRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/repository/LocationScheduleRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/resource/RoomAdministrationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/administration/AmendDecoratedLocationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/administration/CreateDecoratedLocationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/administration/CreateLocationScheduleService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/administration/DecoratedLocationsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/mapping/LocationMappers.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/LocationAttributesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/LocationScheduleTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/RoomAdministrationIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/administration/AmendDecoratedLocationsServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/administration/CreateLocationScheduleServiceTest.kt
Some of this PR includes a bit of tidy up.
> BAVL-672 new endpoint to support updates to room schedule rows.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/LocationAttribute.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/LocationSchedule.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/LocationAttributesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/LocationScheduleTest.kt
Initially I left this as a **TODO**.  Now the probation part is done I have filled that gap for courts at the Domain level.
> BAVL-676 finishing location attribute and schedule checks for courts, this is still needed regardless of how rooms at searched.

- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/nomismapping/NomisMappingClientTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/ModelFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/wiremock/NomisMappingApiMockServer.kt
Test coverage for fix [here](https://github.com/ministryofjustice/hmpps-book-a-video-link-api/pull/400).
> BAVL-676 adding missing test coverage for the NOMIS mapping client.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/locations/availability/DateTimeAvailabilityService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/locations/availability/LocationAvailabilityService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/locations/availability/TimeSlotAvailabilityService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/locations/availability/DateTimeAvailabilityServiceTest.kt
Rooms (locations) for date time lookup will now be sorted according to their priority.
> BAVL-688 changes to sort the rooms for the date and time availability lookup.

- helm_deploy/values-dev.yaml
The supporting cloud platform change is merged for this [here](https://github.com/ministryofjustice/cloud-platform-environments/pull/30487).
> BAVL-695 try app insights fix in dev first. Cloud platform config is merged for this change.

- helm_deploy/values-dev.yaml
Reverts ministryofjustice/hmpps-book-a-video-link-api#413
> Revert "BAVL-695 try app insights fix in dev first. Cloud platform config is merged for this change."

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/probation/ProbationEmailFactory.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/probation/ProbationEmails.kt
- src/main/resources/application-dev.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacadeTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/GovNotifyEmailServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/emails/probation/ProbationEmailFactoryTest.kt
Adding probation officer details and prison room links to (new) amend probation templates, dev only.
> BAVL-711 adding additional information and prison room links in the probation amend emails.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/prisonapi/PrisonApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/prisonersearch/PrisonerSearchClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/PrisonerAppointmentsChangedEventHandler.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/prisonapi/PrisonApiClientTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/ModelFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/InboundEventsIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/wiremock/PrisonApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/wiremock/PrisonerSearchApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/handlers/PrisonerAppointmentsChangedEventHandlerTest.kt
Trying prison API to determine reason for last movement, the prisoner search index is not in sync with the event raised by NOMIS.
> BAVL-752 changed to use prison-api to determine last movement due to race condition with prisoner search indexing.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/LocationSchedule.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/LocationScheduleTest.kt
I have manually tested this locally.
> BAVL-788 fix schedule amend row when save row with no changes.

- src/main/resources/application-dev.yml
- src/main/resources/application.yml
Reverts ministryofjustice/hmpps-book-a-video-link-api#468
> Revert "BAVL-760 enable updated probation cancel, release and transfer email templates containing additional details."

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/ScheduleItem.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/response/ScheduleItem.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/mapping/ScheduleMappers.kt
- src/main/resources/migrations/common/R__v_prison_schedule.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/ScheduleResourceIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/ScheduleServiceTest.kt
Needed for probation CSV extract [Jira](https://dsdmoj.atlassian.net/browse/BAVL-726).
> BAVL-726 adding extra probation officer attributes to the schedule it em required for CSV extract.

- helm_deploy/hmpps-book-a-video-link-api/values.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/config/FeatureSwitches.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/ActivitiesAndAppointmentsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/PrisonService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/EntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/config/FeatureSwitchesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/ActivitiesAndAppointmentsServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/events/PrisonServiceTest.kt
I have kept this change fairly small with regards to impact on code footprint.
I expect we will also have toggles in the various UI's as well anyway.
> BAVL-849 adding a simple feature toggle to switch the mastering of public private notes on/off.

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/client/prisonapi/PrisonApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/ScheduleItem.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/AdditionalBookingDetails.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/AmendVideoBookingRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/CreateVideoBookingRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/request/RequestVideoBookingRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/response/AdditionalBookingDetails.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/response/PrisonAppointment.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/response/ScheduleItem.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/model/response/VideoLinkBooking.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/RequestBookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/mapping/PrisonAppointmentMappers.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/mapping/ScheduleMappers.kt
- src/main/resources/migrations/common/R__v_prison_schedule.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/ModelFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/RequestBookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/ScheduleServiceTest.kt
- utility/feature-toggles-status.sh
The UI for request a booking can be done when this is merged.
> BAVL-886 adding notes to all request and response objects where it was missing.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/VideoBooking.kt
- src/main/resources/migrations/common/V2025.06.11__alter_video_booking.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/entity/VideoBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/EntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/BookingFacadeTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/jobs/CourtHearingLinkReminderJobTest.kt
This is the first PR of a few to add support for new fields for court bookings only, HMTCS number and guest PIN.
These changes are in the Domain layer only.  Next up will be the service and model layers.
> BAVL-925 initial Domain work to introduce new attributes on video booking for HTMCS number and guest pin. Service layer changes to come next.

- src/main/resources/migrations/common/R__v_video_booking_event.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/CsvDataExtractionIntegrationTest.kt
- src/test/resources/integration-test-data/seed-events-by-booking-date-data-extract.sql
We need to show the HMCTS number in the CVP link field in the court CSV if it is provided (instead of a video URL)
> BAVL-925 with the introduction of the HMCTS number we need to show this in the court CSV if this is provided instead of a video URL.

- helm_deploy/hmpps-book-a-video-link-api/templates/reactivate-blocked-locations-cronjob.yaml
- helm_deploy/hmpps-book-a-video-link-api/values.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/repository/LocationAttributeRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/jobs/JobTriggerService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/jobs/Jobs.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/jobs/ReactivateBlockedLocationsJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/locations/administration/DecoratedLocationsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/LocationAttributeTelemetryEvent.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/helper/EntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/integration/resource/JobTriggerIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/jobs/JobTriggerServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/locations/administration/DecoratedLocationsServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsbookavideolinkapi/service/telemetry/LocationAttributeTelemetryEventTest.kt
- src/test/resources/integration-test-data/seed-blocked-locations.sql
The CRON timing for this job is set to run a 1AM in the morning.
It will reactive any temporarily blocked locations where their end date has since passed.
> BAVL-1102 daily morning job to reactivate temporarily blocked locations when their blocked_to date has passed.
